# Datasource
spring:
  datasource:
     url: jdbc:mysql://localhost:3306/empleados_simple

# Username and password
     username: maza
     password: maza

# Keep the connection alive if idle for a long time (needed in production)
     testWhileIdle: true
     validationQuery: SELECT 1

server:
# Puerto aleatorio
#  port: ${PORT:0}
  port: 5555
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
    
 